name: CI Workflow

on:
  push:
    branches:
      - master   
  pull_request:
    branches:
      - master   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing 1'
        run: pwd

      - name: 'Name'
        run: echo youssef

      - name: 'Age'
        run: echo 18

      - name: 'PRINT FOLDER EXISTS'
        run: ls

      - name: Checkout repository
        uses: actions/checkout@v3  
         

      - name: 'printing after action'
        run: ls -a

        

        - name: "Login to Docker Hub"
        run:  docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}


      - name: "Build image"
        run:  docker build -t ${{ secrets.DOCKER_USERNAME }}/youssef_abdelnabe_said .


      - name: "Push to Docker Hub"
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/youssef_abdelnabe_said


