name: CI Workflow

on:
  push:
    branches:
      - master   
  pull_request:
    branches:
      - master   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing 1'
        run: pwd

      - name: 'Name'
        run: echo youssef

      - name: 'Age'
        run: echo 18

      - name: 'PRINT FOLDER EXISTS'
        run: ls
