on:
    push:
      branches:
        - master

  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: 'testing 1'
          run: pwd
  
        - name: 'name'
          run: echo youssef
            
  